"""Agregar docente_id a Curso

Revision ID: 4c11d1996172
Revises: 
Create Date: 2026-05-07 17:33:45.404990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c11d1996172'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('docente_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuarios', ['docente_id'], ['id'])

    with op.batch_alter_table('reportes', schema=None) as batch_op:
        batch_op.alter_column('contenido',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reportes', schema=None) as batch_op:
        batch_op.alter_column('contenido',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)

    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('docente_id')

    # ### end Alembic commands ###
